app/pet/urls.py
from django.conf.urls import url, include

from app.pet.views import listUser, index, pet_view, pet_list, pet_edit, pet_delete,\
	PetList, PetCreate, PetUpdate, PetDelete

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    #url(r'^new$', pet_view, name='pet_create'),
    url(r'^new$', login_required(PetCreate.as_view()), name='pet_create'),
    #url(r'^to_list$', pet_list, name='pet_to_list'),
    #url(r'^to_list$', login_required(PetList.as_view()), name='pet_to_list'),
    url(r'^to_list', login_required(PetList.as_view()), name='pet_to_list'),
    #url(r'^to_edit/(?P<id_pet>\d+)/$', pet_edit, name='pet_to_edit'),
    url(r'^to_edit/(?P<pk>\d+)/$', login_required(PetUpdate.as_view()), name='pet_to_edit'), 
    #url(r'^to_delete/(?P<id_pet>\d+)/$', pet_delete, name='pet_to_delete'),
    url(r'^to_delete/(?P<pk>\d+)/$', login_required(PetDelete.as_view()), name='pet_to_delete'),


    url(r'^list$', listUser, name="list"),
]

mypets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^pet/', include('app.pet.urls', namespace='pet')),

    url(r'^adoption/', include('app.adoption.urls', namespace='adoption')),

    url(r'^all_user/', include('app.all_user.urls', namespace='all_user')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),

    # REGISTRATION BY EMAIL
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
     'email_template_name':'registration/password_reset_email.html'},
      name='password_reset'),

    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},
      name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
     {'template_name':'registration/password_reset_confirm.html'},
      name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
     {'template_name':'registration/password_reset_complete.html'},
      name='password_reset_complete'),

]

app/pet/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models 
 
from app.adoption.models import Person

# Create your models here. 

class Vaccine(models.Model):
	name=models.CharField(max_length=50)

	def __str__(self):
		return '{}'.format(self.name) 

class Pet(models.Model):
	name=models.CharField(max_length=50)
	sex=models.CharField(max_length=10)
	age_approx=models.IntegerField()
	date_recovery=models.DateField()
	person = models.ForeignKey(Person, null=True, blank=True, on_delete=models.CASCADE)
	vaccine=models.ManyToManyField(Vaccine, blank=True)

	 

app/pet/forms.py
from django import forms

from app.pet.models import Pet

class PetForm(forms.ModelForm):
	class Meta:
		model=Pet

		fields=[
			'name',
			'sex',
			'age_approx',
			'date_recovery',
			'person',
			'vaccine',
		]

		labels={
			'name':'Name:',
			'sex':'Sex:',
			'age_approx':'Age(approx):',
			'date_recovery':'Date of Recovery:',
			'person':'Adopter:',
			'vaccine':'Vaccines:',
		}

		widgets={
			'name':forms.TextInput(attrs={'class':'form-control', 'autofocus':True}),
			'sex':forms.TextInput(attrs={'class':'form-control'}),
			'age_approx':forms.TextInput(attrs={'class':'form-control'}),
			'date_recovery':forms.TextInput(attrs={'class':'form-control'}),
			'person':forms.Select(attrs={'class':'form-control'}),
			'vaccine':forms.CheckboxSelectMultiple(),
		}

app/pet/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect


from django.http import HttpResponse

from app.pet.forms import PetForm

from app.pet.models import Pet

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.core.urlresolvers import reverse_lazy

from django.core import serializers

from django.contrib.auth.models import User 

# Create your views here.
def listUser(request):
	list=serializers.serialize('json', User.objects.all(), fields=['first_name', 'last_name', 'email', 'username'])
	return HttpResponse(list, content_type='application/json')

def index(request):
	#return HttpResponse("<h1>Pets</h1>")
	return render(request, 'pet/index.html')

def pet_view(request):
	if request.method=='POST':
		form=PetForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('pet:pet_to_list')
	else:
		form=PetForm()

	return render(request, 'pet/pet_form.html', {'form':form})

def pet_list(request):
	pet=Pet.objects.all().order_by('id')
	context={'pets':pet}
	return render(request, 'pet/pet_list.html', context)

def pet_edit(request, id_pet):
	pet=Pet.objects.get(id=id_pet)
	if request.method=='GET':
		form=PetForm(instance=pet)
	else:
		form=PetForm(request.POST, instance=pet)
		if form.is_valid():
			form.save()
		return redirect('pet:pet_to_list')
	return render(request, 'pet/pet_form.html', {'form':form})

def pet_delete(request, id_pet):
	pet=Pet.objects.get(id=id_pet)
	if request.method=='POST':
		pet.delete()
		return redirect('pet:pet_to_list')
	return render(request, 'pet/pet_delete.html', {'pet':pet})



############################################################################################################################################################

class PetList(ListView):
	model=Pet
	template_name='pet/pet_list.html'
	paginate_by=1

class PetCreate(CreateView):
	model=Pet
	form_class=PetForm
	template_name='pet/pet_form.html'
	success_url=reverse_lazy('pet:pet_to_list')

class PetUpdate(UpdateView):
	model=Pet
	form_class=PetForm
	template_name='pet/pet_form.html'
	success_url=reverse_lazy('pet:pet_to_list')

class PetDelete(DeleteView):
	model=Pet
	template_name='pet/pet_delete.html'
	success_url=reverse_lazy('pet:pet_to_list')

templates/pet/index.html
{% extends 'base/base.html' %}

{% block title %}
	My Pets - App
{% endblock %}

 
{% block content %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1 class="intro">Your Welcome!<br><small> to Pets</small></h1>
		</div> 
	</div>
	
{% endblock %}


templates/pet/pet_delete.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="col-md-10 col-md-offset-2">
		<form action="" method="post">
			{% csrf_token %}
			<!-- <h3>Are you sure that you want to remove from registration? {{ pet.name }} </h3> -->
			<h3>Are you sure that you want to remove from registration? To: <span class="mypet">{{ object.name }}</span> </h3>
			<button type="submit" class="btn btn-danger btn-lg">
	            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
	        </button>
	        <a href="{% url 'pet:pet_to_list' %}" class="btn btn-default btn-lg">
	            <span class="glyphicon glyphicon-triangle-left"></span>&nbsp; Back
	        </a>
		</form> 
	</div>
	
{% endblock %}

templates/pet/pet_form.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="col-md-12">
		<form action="" method="post">
			{% csrf_token %}
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<h1>Pet Form</h1>
					<div class="form-group">
						<label for="">{{ form.name.label }}</label>{{ form.name }}
					</div>
					<div class="form-group">
						<label for="">{{ form.sex.label }}</label>{{ form.sex }}
					</div>
					<div class="form-group">
						<label for="">{{ form.age_approx.label }}</label>{{ form.age_approx }}
					</div>
					<div class="form-group">
						<label for="">{{ form.date_recovery.label }}</label>{{ form.date_recovery }}
					</div>
					<div class="form-group">
						<label for="">{{ form.person.label }}</label>{{ form.person }}
					</div>
					<div class="form-group">
						<label for="">{{ form.vaccine.label }}</label>{{ form.vaccine }}
					</div>

					<button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
				</div>
			</div>
		</form>
	</div>
	<div class="col-md-12"><p>&nbsp;</p></div>
	
{% endblock %}

templates/pet/pet_list.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Pets List</h1>
			<div class="table-responsive table-bordered">
				<table class="table">

					<thead>
						<tr>
							<th>#</th>
							<th>Name</th>
							<th>Sex</th>
							<th>Age</th>
							<th>Date of Recovery</th>
							<th>Adopter</th>
							<th>Actions</th>
						</tr>
					</thead>
					<tbody>
					<!-- {#% if pets %}
					{#% for pet in pets %} -->
					{% if object_list %}
					{% for pet in object_list %}
						<tr>
							<td>{{ pet.id }}</td>
							<td>{{ pet.name }}</td>
							<td>{{ pet.sex }}</td>
							<td>{{ pet.age_approx }}</td>
							<td>{{ pet.date_recovery }}</td>
							<td>{{ pet.person.first_name }} {{ pet.person.last_name }}</td>
							<td>
								<a href="{% url 'pet:pet_to_edit' pet.id %}" class="btn btn-warning btn-xs">
			                        <span class="glyphicon glyphicon-pencil"></span>&nbsp; Edit
			                    </a>
								<a href="{% url 'pet:pet_to_delete' pet.id %}" class="btn btn-danger btn-xs">
			                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
			                    </a>
			                    
							</td>
						</tr>
						{% endfor %}
						{% else %}
							<h2>No records found pets</h2>
						{% endif %}
					</tbody>

				</table> 

			</div>
			<ul class="pager">
				<li>
					{% if page_obj.has_previous %}
						<a href="?page={{ page_obj.previous_page_number }}">Previous</a>
					{% endif %} 
				</li>
				<li>
					{% if page_obj.has_next %}
						<a href="?page={{ page_obj.next_page_number }}">Next</a></li>
					{% endif %}
			</ul>
		</div>
	</div>
	
	
{% endblock %}