app/adoption/urls.py
from django.conf.urls import url 

from app.adoption.views import index_adoption, YourRequestList, YourRequestCreate, YourRequestUpdate, YourRequestDelete

urlpatterns = [
     url(r'^index$', index_adoption),
     url(r'^your_request/to_list$', YourRequestList.as_view(), name='your_request_to_list'),
     url(r'^your_request/new$', YourRequestCreate.as_view(), name='your_request_create'),
     url(r'^your_request/to_edit/(?P<pk>\d+)/$', YourRequestUpdate.as_view(), name='your_request_to_edit'),
     url(r'^your_request/to_delete/(?P<pk>\d+)/$', YourRequestDelete.as_view(), name='your_request_to_delete'),
]



mypets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^pet/', include('app.pet.urls', namespace='pet')),

    url(r'^adoption/', include('app.adoption.urls', namespace='adoption')),

    url(r'^all_user/', include('app.all_user.urls', namespace='all_user')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),

    # REGISTRATION BY EMAIL
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
     'email_template_name':'registration/password_reset_email.html'},
      name='password_reset'),

    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},
      name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
     {'template_name':'registration/password_reset_confirm.html'},
      name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
     {'template_name':'registration/password_reset_complete.html'},
      name='password_reset_complete'),

]

app/adoption/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Person(models.Model):
	first_name=models.CharField(max_length=50)
	last_name=models.CharField(max_length=75)
	age=models.IntegerField()
	phone=models.CharField(max_length=20)
	email=models.EmailField()
	address=models.TextField()


	def __str__(self):
		return '{} {}'.format(self.first_name, self.last_name)


class YourRequest(models.Model):
	person=models.ForeignKey(Person, null=True, blank=True)
	number_pets=models.IntegerField()
	reasons=models.TextField()

app/adoption/forms.py
from django import forms

from app.adoption.models import Person, YourRequest

class PersonForm(forms.ModelForm):
	class Meta:
		model=Person

		fields=[
			'first_name',
			'last_name',
			'age',
			'phone',
			'email',
			'address',
		]

		labels={
			'first_name':'First Name:',
			'last_name':'Last Name:',
			'age':'Age:',
			'phone':'Phone:',
			'email':'Email:',
			'address':'Address:',
		}

		widgets={
			'first_name':forms.TextInput(attrs={'class':'form-control', 'autofocus':True}),
			'last_name':forms.TextInput(attrs={'class':'form-control'}),
			'age':forms.TextInput(attrs={'class':'form-control'}),
			'phone':forms.TextInput(attrs={'class':'form-control'}),
			'email':forms.TextInput(attrs={'class':'form-control'}),
			'address':forms.Textarea(attrs={'class':'form-control'}),
		}

class YourRequestForm(forms.ModelForm):
	class Meta:
		model=YourRequest
		fields=[
			'number_pets',
			'reasons',
		]

		labels={
			'number_pets':'Number of Pets:',
			'reasons':'Reasons to Adoption:',
		}

		widgets={
			'number_pets':forms.TextInput(attrs={'class':'form-control'}),
			'reasons':forms.Textarea(attrs={'class':'form-control'}),
		}

app/adoption/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render


from django.http import HttpResponseRedirect

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from app.adoption.models import Person, YourRequest

from django.core.urlresolvers import reverse_lazy

from app.adoption.forms import PersonForm, YourRequestForm

# Create your views here.



def index_adoption(request):
	return HttpResponse("<h2>Homepage of my app with Django Python Framework.</h2>")

class YourRequestList(ListView):
	model=YourRequest
	template_name='adoption/your_request_list.html'

class YourRequestCreate(CreateView):
	model=YourRequest
	form_class=YourRequestForm
	second_form_class=PersonForm
	template_name='adoption/your_request_form.html'	
	success_url=reverse_lazy('adoption:your_request_to_list')

	def get_context_data(self, **kwargs):
		context=super(YourRequestCreate, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form']=self.form_class(self.request.GET)
		if 'form2' not in context:
			context['form2']=self.second_form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object=self.get_object
		form=self.form_class(request.POST)
		form2=self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			yr=form.save(commit=False)
			yr.person=form2.save()
			yr.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_respose(self.get_context_data(form=form, form2=form2))



class YourRequestUpdate(UpdateView):
	model=YourRequest
	second_model=Person
	form_class=YourRequestForm
	second_form_class=PersonForm
	template_name='adoption/your_request_form.html'
	success_url=reverse_lazy('adoption:your_request_to_list')

	def get_context_data(self, **kwargs):
		context=super(YourRequestUpdate, self).get_context_data(**kwargs)
		pk=self.kwargs.get('pk', 0)
		yr=self.model.objects.get(id=pk)
		p=self.second_model.objects.get(id=yr.person_id)
		if 'form' not in context:
			context['form']=self.form_class()
		if 'form2'not in context:
			context['form2']=self.second_form_class(instance=p)
		context['id']=pk
		return context

	def post(self, request, *args, **kwargs):
		self.object=self.get_object
		id_yr=kwargs['pk']
		yr=self.model.objects.get(id=id_yr)
		p=self.second_model.objects.get(id=yr.person_id)
		form=self.form_class(request.POST, instance=yr)
		form2=self.second_form_class(request.POST, instance=p)
		if form.is_valid() and form2.is_valid():
			form.save()
			form2.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return HttpResponseRedirect(self.get_success_url())


class YourRequestDelete(DeleteView):
	model=YourRequest
	template_name='adoption/your_request_delete.html'
	success_url=reverse_lazy('adoption:your_request_to_list')

templates/adoption/your_request_delete.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="col-md-10 col-md-offset-2">
		<form action="" method="post">
			{% csrf_token %}
			
			<h3>Are you sure that you want to remove from registration? To: <span class="mypet">{{ object.person.first_name }} {{ object.person.last_name }}</span> </h3>
			<button type="submit" class="btn btn-danger btn-lg">
	            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
	        </button>
	        <a href="{% url 'adoption:your_request_to_list' %}" class="btn btn-default btn-lg">
	            <span class="glyphicon glyphicon-triangle-left"></span>&nbsp; Back
	        </a>
		</form> 
	</div>
	
{% endblock %}

templates/adoption/your_request_form.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="col-md-12">
		<form action="" method="post">
			{% csrf_token %}
			
			<div class="row">

				<div class="col-md-8 col-md-offset-2">
					<h1>Apply Form</h1>
					<div class="form-group">
						<label for="">{{ form2.first_name.label}}</label>{{ form2.first_name}}
					</div>
				
					<div class="form-group">
						<label for="">{{ form2.last_name.label}}</label>{{ form2.last_name}}
					</div>

					<div class="form-group">
						<label for="">{{ form2.age.label}}</label>{{ form2.age}}
					</div>

					<div class="form-group">
						<label for="">{{ form2.phone.label}}</label>{{ form2.phone}}
					</div>

					<div class="form-group">
						<label for="">{{ form2.email.label}}</label>{{ form2.email}}
					</div>

					<div class="form-group">
						<label for="">{{ form2.address.label}}</label>{{ form2.address}}
					</div>
					
					<div class="form-group">
						<label for="">{{ form.number_pets.label}}</label>{{ form.number_pets}}
					</div>

					<div class="form-group">
						<label for="">{{ form.reasons.label}}</label>{{ form.reasons}}
					</div>


					<button type="submit" class="btn btn-primary btn-lg btn-block">Send</button>
				</div> 
			</div> 
		</form>

	</div>
	<div class="col-md-12"><p>&nbsp;</p></div>
	
{% endblock %}

templates/adoption/your_request_list.html
{% extends 'base/base.html' %}

{% block content %}
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Adopter List</h1>
			<div class="table-responsive table-bordered">
				<table class="table">

				<thead>
					<tr>
						<th>#</th>
						<th>Adopter</th>
						<th>Number Pets</th>
						<th>Reasons</th>				
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
				<!-- {#% if pets %}
				{#% for pet in pets %} -->
				{% if object_list %}
				{% for yr in object_list %}
					<tr>
						<td>{{ yr.id }}</td>
						<td>{{ yr.person.first_name }} {{ yr.person.last_name }}</td>
						<td>{{ yr.number_pets }}</td>
						<td>{{ yr.reasons }}</td>
						
						<td>
							<a href="{% url 'adoption:your_request_to_edit' yr.id %}" class="btn btn-warning btn-xs">
		                        <span class="glyphicon glyphicon-pencil"></span>&nbsp; Edit
		                    </a>
							<a href="{% url 'adoption:your_request_to_delete' yr.id %}" class="btn btn-danger btn-xs">
		                        <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
		                    </a>
		                    
						</td>
					</tr>
					{% endfor %}
					{% else %}
						<h2>No records found Your Requests</h2>
					{% endif %}
				</tbody>

			</table>
			</div>
		</div>
	</div>
	
	
{% endblock %}