app/adoption/urls.py
from django.conf.urls import url 

from app.adoption.views import index_adoption, YourRequestList, YourRequestCreate, YourRequestUpdate, YourRequestDelete

urlpatterns = [
     url(r'^index$', index_adoption),
     url(r'^your_request/to_list$', YourRequestList.as_view(), name='your_request_to_list'),
     url(r'^your_request/new$', YourRequestCreate.as_view(), name='your_request_create'),
     url(r'^your_request/to_edit/(?P<pk>\d+)/$', YourRequestUpdate.as_view(), name='your_request_to_edit'),
     url(r'^your_request/to_delete/(?P<pk>\d+)/$', YourRequestDelete.as_view(), name='your_request_to_delete'),
]



app/all_user/urls.py
from django.conf.urls import url

from app.all_user.views import RegisterAllUser, UserAPI


urlpatterns = [

	url(r'^to_register$', RegisterAllUser.as_view(), name='to_register'),

	url(r'^api', UserAPI.as_view(), name='api'),

]

app/pet/urls.py
from django.conf.urls import url, include

from app.pet.views import listUser, index, pet_view, pet_list, pet_edit, pet_delete,\
	PetList, PetCreate, PetUpdate, PetDelete

from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', index, name='index'),
    #url(r'^new$', pet_view, name='pet_create'),
    url(r'^new$', login_required(PetCreate.as_view()), name='pet_create'),
    #url(r'^to_list$', pet_list, name='pet_to_list'),
    #url(r'^to_list$', login_required(PetList.as_view()), name='pet_to_list'),
    url(r'^to_list', login_required(PetList.as_view()), name='pet_to_list'),
    #url(r'^to_edit/(?P<id_pet>\d+)/$', pet_edit, name='pet_to_edit'),
    url(r'^to_edit/(?P<pk>\d+)/$', login_required(PetUpdate.as_view()), name='pet_to_edit'), 
    #url(r'^to_delete/(?P<id_pet>\d+)/$', pet_delete, name='pet_to_delete'),
    url(r'^to_delete/(?P<pk>\d+)/$', login_required(PetDelete.as_view()), name='pet_to_delete'),


    url(r'^list$', listUser, name="list"),
]

mypets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^pet/', include('app.pet.urls', namespace='pet')),

    url(r'^adoption/', include('app.adoption.urls', namespace='adoption')),

    url(r'^all_user/', include('app.all_user.urls', namespace='all_user')),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),

    # REGISTRATION BY EMAIL
    url(r'^reset/password_reset', password_reset, {'template_name':'registration/password_reset_form.html',
     'email_template_name':'registration/password_reset_email.html'},
      name='password_reset'),

    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'registration/password_reset_done.html'},
      name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm,
     {'template_name':'registration/password_reset_confirm.html'},
      name='password_reset_confirm'),

    url(r'^reset/done', password_reset_complete,
     {'template_name':'registration/password_reset_complete.html'},
      name='password_reset_complete'),

]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	{% block extrahead %} {% endblock %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Oswald:300,400,700" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700" rel="stylesheet" type="text/css">
	<link rel="stylesheet" href="{% static 'css/default.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<meta charset="UTF-8">
	<title>{% block title %}Document{% endblock %}</title>
</head>
<body>
	{% block navbar %}
		<nav class="navbar navbar-default">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="{% url 'pet:index' %}">MyPets</a>
	    </div>

	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        
	        
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pets <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="{% url 'pet:pet_create' %}">Register</a></li>
	            <li><a href="{% url 'pet:pet_to_list' %}">All List</a></li> 
	          </ul>
	        </li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-heart"></span>&nbsp; Adoptions <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	            <li><a href="{% url 'adoption:your_request_create' %}">Apply for</a></li>
	            <li><a href="{% url 'adoption:your_request_to_list' %}">Requests List</a></li> 
	          </ul>
	        </li>
	      </ul>
	      
	      <ul class="nav navbar-nav navbar-right">
	      	<li><a href="{% url 'pet:index' %}"><span class="glyphicon glyphicon-home"></span>&nbsp; Homepage</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span>&nbsp; My Account <span class="caret"></span></a>
	          
			            
			  
	          <ul class="dropdown-menu" role="menu">
	          	{% if user.is_authenticated %}
	            	<li><a href="{% url 'logout' %}">Sign Out</a></li>
	            	<li><a href="{% url 'password_reset' %}">Recover Password</a></li>
	            {% else %}
					<li><a href="{% url 'login' %}">Sign In</a></li>
	          		<li><a href="{% url 'all_user:to_register' %}">Sign Up</a></li>
	            {% endif %}
	          </ul>
	          
	        </li>
	      </ul>
	    </div>
	  </div>
	</nav>
	{% endblock %}
	<div class="container">
		<div class="user">
			{% if user.is_authenticated %}
				Welcome <span>{{ user.username }}</span> !!
			{% else %}
				&nbsp;
			{% endif %}
		</div>
		
		<div class="row">
			<div class="col-md-12">
				{% block content %}
					<h5>This is content of the base.</h5>
				{% endblock %}
			</div>		
			
			
		</div>
	</div>
	<div class="text-center footer">
		{% block footer %}
			{% now "Y" %}, &copy;copyright MS 
		{% endblock %}
	</div>


	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	
	{% block extrajs %}
		
	{% endblock %}
</body>
</html>